version: '3'


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: conduit_local_django
    container_name: django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  